### ISSUE TITLE
Deployment: to CU

### ISSUE THREAD

**Issue by ChrisEsterlein** [cires-ncei/metadata-catalog#26]
Goal:
Deploy docker image to the CU test infrastructure via docker swarm

Open questions:
- Should we publish images for our modules to the docker hub?
- Should we use compose v3 to utilize docker swarm on the CU servers?
- Should the deployment configuration even be a part of this project?

A rough plan:
- add dockerImage to api module
- upgrade docker to 3 so swarm is built in
- create root level docker-compose.yml 
// create docker-compose.yml using version 3 and the deploy options
- check that we won't have conflicts with onestop
- attempt to deploy to cu manually using local client and images

**Comment by zebdelk** [comment]
Due to the size of the items in this story, and agreement that the work done in #83 pull request was a good match for our target-size of stories, I created a series of follow up stories to address additional work needed to get the deployment in place: 

- #89 
- #91  (arguably a task in the admin repo)
- #90 (ditto)
- #92 
- #93 
- #94
